---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-fis-marketmap
  labels:
    app: back-fis-marketmap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-pod
  template:
    metadata:
      name: back-pod
      labels:
        app: back-pod
    spec:
      containers:
        - name: back-image
          image: dhakerkarous/back-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: MONGO_URI
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: PORT
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: EMAIL
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: PASSWORD
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: my-secrets
                  key: FRONTEND_URL
---
apiVersion: v1
kind: Service
metadata:
  name: back-fis-marketmap
  labels:
    app: back-fis-marketmap
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 32322
  selector:
    app: back-pod