---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-tma2
  labels:
    app: back-tma2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-pod
  template:
    metadata:
      name: back-pod
      labels:
        app: back-pod
    spec:
      containers:
        - name: back-image
          image: dhakerkarous/back-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: MONGO_URI_PLACEHOLDER
            - name: PORT
              value: 3000
            - name: EMAIL
              value: EMAIL_PLACEHOLDER
            - name: PASSWORD
              value: PASSWORD_PLACEHOLDER
            - name: FRONTEND_URL
              value: http://192.168.181.128:32321

---
apiVersion: v1
kind: Service
metadata:
  name: back-tma2
  labels:
    app: back-tma2
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 32322
  selector:
    app: back-pod