apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-tma
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: front-tma
    spec:
      containers:
        - name: react-docker
          image: dhakerkarous/react-docker:latest
          ports:
            - containerPort: 80
              name: http-port
          env:
            - name: MONGO_URI
              value: "MONGO_URI"
            - name: EMAIL
              value: "EMAIL"
            - name: PASSWORD
              value: "PASSWORD"
            - name: FRONTEND_URL
              value: "http://192.168.181.128:32321"
  selector:
    matchLabels:
      app: front-tma
